
name: MLCServerApp
options:
  deploymentTarget:
    iOS: "18.5"
settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual
    TARGETED_DEVICE_FAMILY: "1,2"
    PRODUCT_BUNDLE_IDENTIFIER: com.example.mlcserver
    INFOPLIST_FILE: MLCServerApp/Info.plist
    OTHER_LDFLAGS:
      - "-Wl,-all_load"
      - "-lmodel_iphone"
      - "-lmlc_llm"
      - "-ltvm_runtime"
      - "-ltokenizers_cpp"
      - "-lsentencepiece"
      - "-ltokenizers_c"
    LIBRARY_SEARCH_PATHS:
      - "$(SRCROOT)/dist/lib"
targets:
  MLCServerApp:
    type: application
    platform: iOS
    sources:
      - path: MLCServerApp
      - path: dist/bundle
        type: folder
    dependencies:
      - framework: dist/framework/MLCSwift.xcframework
        embed: true
    scheme:
      testTargets: []
    settings:
      base:
        CODE_SIGN_IDENTITY: iPhone Developer
